const colors = {
  light: {
    text: "#0F1A2C",
    tint: "#00205B",
    background: "#FAFAF8",
    foreground: "#0F1A2C",
    card: "#FFFFFF",
    cardForeground: "#0F1A2C",
    primary: "#00205B",
    primaryForeground: "#FFFFFF",
    secondary: "#E03C31",
    secondaryForeground: "#FFFFFF",
    muted: "#EEF2F7",
    mutedForeground: "#6B7A99",
    accent: "#F9BD0A",
    accentForeground: "#0F1A2C",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDE5F0",
    input: "#DDE5F0",
  },
  dark: {
    text: "#F0F4FA",
    tint: "#4D7FFF",
    background: "#0A1626",
    foreground: "#F0F4FA",
    card: "#0F2038",
    cardForeground: "#F0F4FA",
    primary: "#4D7FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#E03C31",
    secondaryForeground: "#FFFFFF",
    muted: "#162235",
    mutedForeground: "#8A9EC0",
    accent: "#F9BD0A",
    accentForeground: "#0F1A2C",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3050",
    input: "#1E3050",
  },
  radius: 12,
};

export default colors;
